name: LMT

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
jobs:
  check-for-broken-links:
    runs-on: thomaszahner/lmt
    steps:
      - uses: actions/checkout@v1
      - name: Check for broken links
        run: |
          set +e
          lmt check ./**/*.md
